name: deploy-frontend

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Deploy target"
        required: true
        type: choice
        options: [yamada, arako]
        default: yamada

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-frontend
  cancel-in-progress: true

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set env (yamada)
        if: ${{ github.event.inputs.env == 'yamada' }}
        run: |
          echo "S3_BUCKET=mtr-map-spa" >> $GITHUB_ENV
          echo "ROLE_TO_ASSUME=arn:aws:iam::016944483672:role/github-actions-deploy-frontend" >> $GITHUB_ENV

      - name: Set env (arako)
        if: ${{ github.event.inputs.env == 'arako' }}
        run: |
          echo "S3_BUCKET=TODO" >> $GITHUB_ENV
          echo "ROLE_TO_ASSUME=TODO" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: mtr-front/mattero_map/package-lock.json

      - name: Install
        run: npm ci

      # out/ を作る（Next.js export 想定）
      - name: Build
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync ./out s3://${{ env.S3_BUCKET }}/ --delete
